# Generated by Django 4.2.17 on 2025-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelegramId', models.BigIntegerField()),
                ('Fullname', models.CharField(max_length=32, null=True)),
                ('UserType', models.CharField(choices=[('pupil', 'Ученик'), ('teacher', 'Учитель')], max_length=7, null=True)),
            ],
        ),
    ]
