# Generated by Django 4.2.17 on 2025-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_classrooms_users_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='Name',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='Letter',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='Number',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
