# Generated by Django 5.1.5 on 2025-01-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_remove_classrooms_name_classrooms_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница')])),
                ('Classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleDays', to='Models.classrooms')),
            ],
            options={
                'ordering': ['DayOfWeek'],
                'unique_together': {('Classroom', 'DayOfWeek')},
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.PositiveSmallIntegerField()),
                ('SubjectName', models.CharField(max_length=50)),
                ('ScheduleDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='Models.scheduledays')),
            ],
            options={
                'ordering': ['Order'],
            },
        ),
    ]
